### PR TITLE
make the CMake_WASM example work again

### PR DESCRIPTION
**Pull request by mhaberler**
this works for me including in-browser C-level debugging with the modified `lgfx::Panel_sdl` API 

unsure if this is the right way to do it - grateful for a review

### CODE REVIEW

**Comment by tobozo** [comment]
thanks :+1: 

I will try to add a github workflow to test the WASM example and prevent code erosion in the future, I'm a complete noob with WASM too :hand_over_mouth: and this is the perfect occasion to learn more 

can you confirm these are the steps to follow:

   - git clone https://github.com/emscripten-core/emsdk.git
   - cd emsdk
   - ./emsdk install latest # any specific version?
   - ./emsdk activate latest
   - source ./emsdk_env.sh
   - cd examples_for_PC/CMake_WASM
   - mkdir build
   - cd build
   - emcmake cmake ..
   - emmake make
   - publish html/js/wasm on github pages

**Comment by mhaberler** [comment]
yes, that is the steps I followed - no specific version, just latest


have a look at the notes in the README - very useful tutorial referenced there
install Chrome Canary and the extension as outlined, then try debugging in Canary

**Comment by tobozo** [comment]
> install Chrome Canary and the extension as outlined

that's for local testing, right? while it makes sense to mention it in the readme, the github workflow probably won't need that as the assets will be [published on github pages](https://github.com/actions/deploy-pages)

**Comment by mhaberler** [comment]
nope, local testing only - nothing todo with this repo

**Comment by tobozo** [comment]
puslishing to github-pages seems to work on [my fork](https://tobozo.github.io/LovyanGFX/WASM/)

**Comment by mhaberler** [comment]
excellent!

**Comment by mhaberler** [comment]
hm, try this with Canary:  https://static.mah.priv.at/public/lovyan.html
I can source-debug that:
image


I cannot with yours:  https://tobozo.github.io/LovyanGFX/WASM/ , unclear why:
image

I guess this is the filepath mapping issue mentioned in the tutorial

anyway good to go!

**Comment by tobozo** [comment]
oh the workflow only published the index.html file, more files are required maybe?

I try to keep my machine Chrome-free so I didn't test with the extension :wink:

**Comment by mhaberler** [comment]
no I dont think so, I just pushed index.html to my server

it seems SINGLE_FILE=1 wraps all assets including DWARF info into the wasm blob
could be an artefact of running a remote builder causing path name divergence

**Pull request merged**
