### PR TITLE
Adjust default touch calibration for Core2

### PR DESCRIPTION
**Pull request by toyoshim**
p->touch(t) call invokes Panel_Device::touchCalibrate and results in setting up the affine matrix to map the touch geometry into the panel one. This is not preferable as the touch geometry contains the virtual screen panel area outside the panel area.

This patch changes the order to call setCalibrateAffine with dedicated parameters for Core2 to overwrite the default unexpected matrix.

### CODE REVIEW

**Comment by tobozo** [comment]
hi, thanks for your contribution :+1: 

I'm not sure I understand the changes (didn't observe any anomaly before) how can I reproduce the issue this PR addresses?

**Comment by toyoshim** [comment]
Hi, I will prepare an example project with that you can reproduce the issue.
I'll be back here once it's ready.

**Comment by toyoshim** [comment]
https://github.com/toyoshim/LovyanGFXTest/blob/main/src/main.cc
Here is an ESPIDP project and test code for PlatformIO/Code.
Please check my comment on main.cc and console logs shown on running it and touching the screen.

**Comment by tobozo** [comment]
after doing some research it appears changing the calibration sequence order will impact existing projects relying on the current behaviour

      // Current getTouch() never returns a point that is recognized as in the
      // virtual screen button area.

this is by design, getTouch() and getTouchRaw() are supposed to behave differently, the former is constrained to the lcd area while the latter is constrained to the touch area

supporting the touch zone outside the lcd area with M5Core2 can be done as follows:

```cpp
auto ms = lgfx::millis();
if (Touch.isEnabled()) {
  Touch.update(ms);
  int i = Touch.getCount();
  while (--i >= 0) {
    auto raw = Touch.getTouchPointRaw(i);
    if( raw.y > lcd.height() ) {
      // (raw.x, raw.y) touch point is in the M5Core2 buttons area
    }
  }
}
```

**Comment by toyoshim** [comment]
getTouch() returns adjusted points per the calibrated or restoed affine matrix, and getTouchRaw() returns the original point.
So, I understand they could return different points. But the problem exists in the default calibration logic for Core2.

https://twitter.com/lovyan03/status/1721701020118695948
Here is a thread lovyan and I discussed this, and he expects if we touch outside the Panel, getTouch() is expected to return a point outside the Panel rather than adjusted point that is scaled to map on the Panel, so that we can also handle the virtual screen buttons through the getTouch() API. This behavior is aligned with the behavior after users do a manual calibration.

**Comment by tobozo** [comment]
interesting, somehow I believed that getTouch returned a constrained value rather than a scaled value, so this means that any UI code relying on the assumption that [touch height == display height](https://github.com/lovyan03/LovyanGFX/blob/master/examples/Advanced/LVGL_PlatformIO/src/main.cpp#L44) is wrong ?

**Comment by toyoshim** [comment]
yeah, actual behavior is returning a scaled value rather than saturated/constrained value, i.e. `touch.y * panel.height / touch.height`. So, if I draw pixels on touching points, they are drawn at slightly shifted point in the y direction.

**Comment by toyoshim** [comment]
Hi, is there anything I can do here to move the discussion forward?
or shall we close as work-as-intended? In such a case, I can have a workaround in my application end, as I just need to reinitialize the calibration setting after the library's initialization.

**Comment by tobozo** [comment]
let's keep this PR opens until @lovyan03 gives the final word

**Comment by toyoshim** [comment]
ok, sounds good.
thanks!

**Comment by tobozo** [comment]
bump

**Comment by lovyan03** [comment]
Sorry for the long wait, and thank you for submitting this pull request...!

**Pull request merged**
