### PR TITLE
Add support for TTGO T-Display

### PR DESCRIPTION
**Pull request by zingo**
Hi I added the TTGO TDisplay device, if you want this abd want me to clean it up more just let me know.
(I have only tested v1 and Autodetect)

### CODE REVIEW

**Comment by zingo** [comment]
I'm not sure if the rotation is good? I have just tested with build_test.ino (platormio) and since is was only gfx in that test the default  rotation might be very narrow and tall instead of wide and not so tall, 
e.g. I don't know if you prefere a added cfg.offset_rotation = 2; or smilar.

**Comment by lovyan03** [comment]
@zingo 
Thank you for your pull request.
The master branch is only used for release, so please make the pull request for the develop branch.
The offset_rotation should be 0. Normally this does not need to be changed.

**Comment by zingo** [comment]
Thanks, Ill re-pull request it

**Comment by lovyan03** [comment]
@zingo @tobozo 
Thank you very much !

**Comment by zingo** [comment]
Thanks a lot, was going to do a local rebase-upload->pull request after work today, didn't know you could just change it so easy :)

**Pull request merged**
