### PR TITLE
Enable stdio filesystem support

### PR DESCRIPTION
**Pull request by MitchBradley**
It was commented out.  Uncommenting it and adding a namespace qualifier to load_font_with_path made it work great.  Tested with platformio native builds on Windows/Mingw32

I'm not sure why it was not enabled.  My guess is that it failed to compile due to the missing Base:: on load_font_with_path(), and nobody had time to track down that problem.

### CODE REVIEW

**Comment by MitchBradley** [comment]
IDF builds are still failing.  I'm trying to think of a way to enable filesystem support for native builds without making ESP-IDF choke.

**Comment by MitchBradley** [comment]
Okay, it passes CI now.  It would be nice to say something like "#if HAS_FILE_WRAPPER" but that would require some extra work elsewhere in the code base.

If this patch is accepted, what is the best way to propagate it to M5GFX ?

**Comment by tobozo** [comment]
hi and thanks for your contribution :+1: 

please edit your PR to use the `develop` branch both as base and target

**Comment by MitchBradley** [comment]
Closing this in favor of #536 which is based on develop

**Pull request closed without merging**
