### PR TITLE
Add GC9307 panel.

### PR DESCRIPTION
**Pull request by lbuque**
Tested the panel successfully using esp32c3.

Snipaste_2024-11-14_01-31-26

But I used esp32c6 to test and some problems occurred. Please refer to #644

### CODE REVIEW

**Comment by tobozo** [comment]
hi, thanks for testing this :+1:

can you please use the [`develop`](https://github.com/lovyan03/LovyanGFX/tree/develop) branch as source and target for your pull request

you'll probably have to open a new PR and close this one, sorry about that

**Comment by lbuque** [comment]
@tobozo I have followed your suggestion and requested PR to be merged into devlop

**Comment by tobozo** [comment]
thanks!

did this PR also address the ESP32-C6 issue?

**Comment by lovyan03** [comment]
oh no... 
image

@lbuque 
Adding offsets should be done in the panel settings and not hard coded into the program.
We would like to remove these offsets.

**Comment by lbuque** [comment]
@lovyan03 Yes, because it is flawed.

**Comment by lovyan03** [comment]
@lbuque 
 flawed ? 
I don't understand what it means.

**Comment by lbuque** [comment]
@lovyan03 The code I submitted earlier was not perfect.

**Comment by lovyan03** [comment]
@lbuque 
Who will do it?

**Pull request merged**
