### PR TITLE
Remove unneeded i2c write

### PR DESCRIPTION
**Pull request by zingo**
Hi
For some reason I got a 1s freeze on my i2c on every touch event on a ESP32 WT32-SC01 the i2c that freezed was on other pins and should not be realted. So this is it was really strange, maybe some problem in the lover layer ESP I2C libs compared to maybe using different i2c drivers?  While debugging my problem I found that if I removing this write it helps and as this write is not need anyway it is kind of a smal code cleanup patch anyway. :)

Some other day I probably need to figure out the real problem causing the 1s delay I got.

### CODE REVIEW

**Comment by lovyan03** [comment]
@zingo 
Thank you for your PR.

There is a reason for this seemingly strange implementation.
Somehow the polling mode sometimes changed on a whim, so I implemented a work-around of reconfiguring the mode when the touch response changed.
I will test this again later, but I will probably not merge this.

**Comment by zingo** [comment]
Ah good to know, thanks for remebering this, it could have tricky to find if merged . I was also wondering if a reconfigure of the touch chip might be needed after a sleep.

Ill try to find a better (proper) solution too my original problem, e.g. geting 1s delay :) 

I digged deeper into it and If I put the i2c in read mode directly after the line I removed e.g.
`        
_write_reg(FT5x06_INTMODE_REG, 0x00); // INT Polling mode
if (lgfx::i2c::beginTransaction(_cfg.i2c_port, _cfg.i2c_addr, _cfg.freq, true))  // put GPIO in READ mode
{
    lgfx::i2c::endTransaction(_cfg.i2c_port).has_value();
}
`
I don't get the 1s delay. Im trying to dig into esp32 i2c code too see if it just rely on it being in read, or if it's a scheduling thing making the esp32 i2c code and your i2c overlap someway in time. I see if I can find mode info :)

**Comment by lovyan03** [comment]
umm.
I am not aware of the situation you are describing.
If you think there is something wrong, please create an Issue that describes the code and assumptions that can reproduce the problem.

**Comment by zingo** [comment]
Yes I'm still investigating and if I find something to improve I create a new patch or ticket, you can close this one. 

Currently I think it might have to do with mpu6050_light using twowire for i2c at the same interface as LovyanGFX i2c. I spent some time looking at your code and it seems to setup all stuff regarding the i2c really god in beginTransmission() but I'm not so sure the other library does that yet, plan to check that next. 

If I add a call to your beginTransmission(...,true e.g. read) before their code it works, Ill try to figure out the minimum thing I need to do to get it to work,l then it would be easy to check thire setup.

I also might switch 100% to your i2c code in the rest of my project, it would probably avoid the problem and save some space, but it's also nice to be able to use a untouched mpu6050_light so it can be updated by platformIO when new upstream versions appear, we will see how this ends up.

Thanks for your help.

**Comment by lovyan03** [comment]
Just to be sure, are multiple processes trying to access I2C at the same time in a multi-threaded fashion?
If so, the exclusion control needs to be implemented on the user side.

I would like to implement I2C exclusive control, but I have to find a way to get exclusive control rights from the ArduinoESP32 and ESP-IDF I2C drivers.
However, their drivers vary widely from version to version, so my plan has failed so far.

I won't stop you from relying on LovyanGFX's I2C driver, but I don't recommend it because LovyanGFX's internal implementation is likely to change through updates.
I am considering producing a new library `LovyanHAL` that takes out only HAL, and in the future `LovyanGFX v2` will use `LovyanHAL`.

**Comment by zingo** [comment]
> Just to be sure, are multiple processes trying to access I2C at the same time in a multi-threaded fashion?

In my case I was quite sure they access I2C after each other, I I think the twowire might not setup/restore everything on it's next "begin". I would be nice to add a patch to fix it (wherever it makes more sense) but I also kind of might ignore it as I have already pend way more time ot it if it's only me who is interested and use your i2c code (and of cause be prepared that it's not stable, that comletly ok). The limited usage twowire in my project would probably be easy ported or maybe I create a dumb copy of the twowire class that just call your code. 

Just for future reference if someone search and find this in the futrure and have the same problem and want to continu the seach this what I found was the minimal code I needed to add to your code to get twowire work in the next read(and not timeout for 1s). I do NOT in any way recomend to add this to your code, it was just a way for me to see what was needed to avoid the problem before I checked the  twowire code. I also hacked it into transactionWrite() as it was part of my problematic callchain and the only place where  transactionWrite()  was called in my case so it was just convinent ,but I know it's a super ugly change.

```
    cpp::result<void, error_t> transactionWrite(int i2c_port, int addr, const uint8_t *writedata, uint8_t writelen, uint32_t freq)
    {
      cpp::result<void, error_t> res;

      if ((res = beginTransaction(i2c_port, addr, freq, false)).has_value()
       && (res = writeBytes(i2c_port, writedata, writelen)).has_value()
      )
      {
        res = endTransaction(i2c_port);
      }
#if 1
      log_printf("transactionWrite() --------------------------------------------- uglu patch for test!\n");
      auto dev = getDev(i2c_port);
      auto fifo_addr = getFifoAddr(i2c_port);
      *fifo_addr = addr << 1 | I2C_MASTER_READ;
      i2c_set_cmd(dev, 0, i2c_cmd_start, 0);
      i2c_set_cmd(dev, 1, i2c_cmd_write, 1);
      i2c_set_cmd(dev, 2, i2c_cmd_end, 0);

      dev->ctr.trans_start = 1;
#endif
      return res;
    }
```

**Comment by zingo** [comment]
The easies way to solve this turned out to be to just add a begin/end call to TwoWire around my usage of it e.g. something like
```
static TwoWire I2C_0 = TwoWire(0);

loop()
{
I2C_0.begin(SDA_0 , SCL_0 , I2C_FREQ);
... my MPU6050 stuff
... my other TwoWire stuff ( my AW9523 driver)
I2C_0.end();

gfxUpdateLoopHandler(); //handling LVGL and LovyanGFX stuff
...
// The rest of the logic in on my device
}
```
That is a kind of clean solution as each user of the I2C gets separated compleatly. I don't think the extra begin()/end() is a problem speed wise in my setup but if so I adress that later.

Thanks for your time.

**Comment by lovyan03** [comment]
I have updated the develop branch with a fix related to this issue.
With any luck, the bug may have been resolved.

**Comment by zingo** [comment]
I still have the problem but I don't think its up to LovyanGFX to need to fix it:) In the end it's me who mix 2 i2c drivers in my project :)
The added 
```
I2C_0.begin(SDA_0 , SCL_0 , I2C_FREQ);
...
I2C_0.end();
```
In the loop only "cost" 0.5ms on my system and get more spped then I need anyway :)
I have no problem with closing this if you like.
Thanks for your help!

**Pull request closed without merging**
