### PR TITLE
- Add panel instruction to version ESP32-4848S040 by GUITION manufactu…

### PR DESCRIPTION
**Pull request by FigueiredoStable**
Added support to the board ESP32-4848S040 i buyed this board from this link: 

https://pt.aliexpress.com/item/1005006335587633.html?spm=a2g0o.order_list.order_list_main.53.21efcaa4QVxg0a&gatewayAdapt=glo2bra

They have some instruction changes compared to Panel_ST7701 implemented by default.

This is a image from board:

971639B2-4FC4-41CF-A686-3E82BFD55B0F

With the default Panel_ST7701:

FD656371-C06C-403B-A00E-3FD29255FF97

Now with the Panel_ST7701_gution_esp32_4848S040:

6B443387-C58F-4529-8518-D653D0CE62EA

I don't know if is the best name to functions and the header struct, i can't finded informations to be assertive with this.

Thank you in advance for the project, I hope to be able to contribute more.

### CODE REVIEW

**Comment by tobozo** [comment]
hi, thanks for your contribution 👍 

Can you please edit (or resubmit) your PR using the `develop` branch as base and target?

**Comment by FigueiredoStable** [comment]
Hi, changed to develop.

Tks

**Comment by tobozo** [comment]
btw the logo on the board reads "guition", not "gution"

**Comment by FigueiredoStable** [comment]
> btw the logo on the board reads "guition", not "gution"

Changed to correct name, tks.

**Comment by tobozo** [comment]
thanks :+1: 

this PR is still based on the master branch from your fork though, this will get some CI jobs to fail, can you please adjust it so that both source and target use the `develop` branch?

**Comment by FigueiredoStable** [comment]
> thanks 👍
> 
> this PR is still based on the master branch from your fork though, this will get some CI jobs to fail, can you please adjust it so that both source and target use the `develop` branch?

I seeid it now, my fork only contemply master branch (my fault) now is better close this PR and i fork from develop and submit again? i tried to update my fork with the others branchs, but i have no success.

**Comment by tobozo** [comment]
yep this github option to only clone the main branch is really annoying :grimacing: last time this happened I had to delete the fork and re-fork the project with the option checked

**Comment by FigueiredoStable** [comment]
> yep this github option to only clone the main branch is really annoying 😬 last time this happened I had to delete the fork and re-fork the project with the option checked

Another learning experience hehe, thankfully there are few additions that I will make again in the development field. Thank you again.

**Pull request closed without merging**
