### PR TITLE
[WIP] SDL panel porting

### PR DESCRIPTION
**Pull request by imliubo**
Did some simple work, now we can test and simulate LGFX by using SDL. 

Currently only tested on Linux Mint system.

[Demo](https://twitter.com/its_hard_2_name/status/1499043321548730369)

### CODE REVIEW

**Comment by tobozo** [comment]
seems to compile on Ubuntu

```
#> ~/src/LovyanGFX/examples/Advanced/CMake_SDL$ cmake .
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: ~/src/LovyanGFX/examples/Advanced/CMake_SDL
```

it created a CMake_SDL folder with those files, but I'm not sure how to use that, does it require a SDL project to integrate with?


image

**Comment by imliubo** [comment]
sorry for reply late.

## dependency:
```bash
sudo apt-get install build-essential libsdl2-dev libsdl2-2.0-0
```

## CMakeLists.txt(need pay attention to "path/to" in this file)
```CMakeLists
cmake_minimum_required (VERSION 3.8)
project(LGFXFB)

file(GLOB Target_Files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS 
    *.cpp
    /path/to/LovyanGFX/src/lgfx/Fonts/efont/*.c
    /path/to/LovyanGFX/src/lgfx/Fonts/IPA/*.c
    /path/to/LovyanGFX/src/lgfx/utility/*.c
    /path/to/LovyanGFX/src/lgfx/v1/*.cpp
    /path/to/LovyanGFX/src/lgfx/v1/misc/*.cpp
    /path/to/LovyanGFX/src/lgfx/v1/panel/*.cpp
    /path/to/LovyanGFX/src/lgfx/v1/platforms/sdl/*.cpp
    )

find_package(SDL2 REQUIRED SDL2)
include_directories(${SDL2_INCLUDE_DIRS})

add_executable (LGFXFB ${Target_Files})
target_include_directories(LGFXFB PUBLIC "/path/to/LovyanGFX/src/")
target_compile_features(LGFXFB PUBLIC cxx_std_17)
target_link_libraries(LGFXFB -lpthread ${SDL2_LIBRARIES})
```
## build and run (in CMake_SDL dir)
```bash
mkdir build && cd build && cmake ..
make
./LGFXFB  # this is a mistake, change to LGFXSDL would be better
```

**Comment by tobozo** [comment]
thanks!

it works much better with the absolute path in the file GLOB :tada: 

I run `cmake . && make` from the `CMake_SDL` folder, didn't need to create the `build` folder, the `make` command fails when I run it from there anyway.

Also I'm using this: 

`target_include_directories(LGFXFB PUBLIC "../../../../LovyanGFX/src/")`

I tried to add such paths in the file GLOB to no luck: if this project could work without editing the CMakeLists.txt from the source, it could easily be added to the workflow checks (see github actions) and compiled automatically on push/pull-request.

**Comment by tobozo** [comment]
plasma demo code for LGFX+SDL2

```C++
#define LGFX_USE_V1
#include <LovyanGFX.hpp>
#include <LGFX_AUTODETECT.hpp>

#define canvasWidth  320
#define canvasHeight 240

LGFX lcd ( canvasWidth, canvasHeight );
LGFX_Sprite *canvas = new LGFX_Sprite( &lcd );

uint32_t *fb; // frame buffer
uint8_t *plasma; // pointer to plasma array

uint32_t plasmaPalette[] = {
  63488, 63520, 63584, 63616, 63680, 63712, 63776, 63808, 63872, 63904, 63968, 64000, 64064, 64096, 64160, 64192,
  64224, 64288, 64320, 64384, 64416, 64480, 64512, 64576, 64608, 64672, 64704, 64768, 64800, 64864, 64896, 64960,
  64992, 65056, 65088, 65152, 65184, 65248, 65280, 65344, 65376, 65440, 65472, 65504, 63456, 63456, 61408, 59360,
  57312, 57312, 55264, 53216, 51168, 51168, 49120, 47072, 45024, 45024, 42976, 40928, 38880, 38880, 36832, 34784,
  32736, 32736, 30688, 28640, 26592, 26592, 24544, 22496, 22496, 20448, 18400, 16352, 16352, 14304, 12256, 10208,
  10208, 8160,  6112,  4064,  4064,  2016,  2016,  2017,  2018,  2018,  2019,  2020,  2021,  2021,  2022,  2023,
  2024,  2024,  2025,  2026,  2026,  2027,  2028,  2029,  2029,  2030,  2031,  2032,  2032,  2033,  2034,  2035,
  2035,  2036,  2037,  2038,  2038,  2039,  2040,  2041,  2041,  2042,  2043,  2044,  2044,  2045,  2046,  2047,
  2047,  2015,  1951,  1919,  1855,  1823,  1759,  1727,  1663,  1631,  1567,  1535,  1471,  1439,  1375,  1343,
  1279,  1247,  1183,  1151,  1087,  1055,  991,   959,   895,   863,   799,   767,   703,   671,   639,   575,
  543,   479,   447,   383,   351,   287,   255,   191,   159,   95,    63,    31,    2079,  2079,  4127,  6175,
  8223,  8223,  10271, 12319, 14367, 14367, 16415, 18463, 20511, 20511, 22559, 24607, 24607, 26655, 28703, 30751,
  30751, 32799, 34847, 36895, 36895, 38943, 40991, 43039, 43039, 45087, 47135, 49183, 49183, 51231, 53279, 55327,
  55327, 57375, 59423, 61471, 61471, 63519, 63519, 63518, 63517, 63517, 63516, 63515, 63514, 63514, 63513, 63512,
  63511, 63511, 63510, 63509, 63508, 63508, 63507, 63506, 63505, 63505, 63504, 63503, 63502, 63502, 63501, 63500,
  63499, 63499, 63498, 63497, 63497, 63496, 63495, 63494, 63494, 63493, 63492, 63491, 63491, 63490, 63489, 63488,
};


void initPlasma()
{
  for ( uint32_t y = 0; y < canvasHeight; y++) {
    for ( uint32_t x = 0; x < canvasWidth; x++) {
      plasma[ y * canvasWidth + x ] = (
        128.0 + ( 128.0 * cos ( x / 16.0 ) )
        - 128.0 + (128.0 * sin ( y / 32.0 ) )
        - 128.0 + (128.0 * sin(sqrt((x - canvasWidth / 2.0)* (x - canvasWidth / 2.0) + (y - canvasHeight / 2.0) * (y - canvasHeight / 2.0)) / 8.0))
        ) / 3;
    }
  }
}


void drawPlasma( uint8_t paletteShift )
{
  for ( uint32_t y = 0; y < canvasHeight; y++) {
    for ( uint32_t x = 0; x < canvasWidth; x++) {
      int colorIndex = ( plasma[ y * canvasWidth + x ] + paletteShift ) % 256;
      // convert 16bit palette color to 32bit colorspace
      uint16_t c = plasmaPalette[ colorIndex ];
      uint8_t r = uint8_t(((c & 0xF800) >> 11) << 3);
      uint8_t g = uint8_t(((c & 0x7E0) >> 5) << 2);
      uint8_t b = uint8_t(((c & 0x1F)) << 3);
      fb[ y * canvasWidth + x ] = (int(r)<<24) + (int(g)<<16) + (int(b)<<8) + int(0xff);
    }
  }
  canvas->pushSprite(0,0);
}


void setup()
{
  lcd.init();

  SDL_Log("LGFX SDL Display [%d*%d@%dbpp]\n", lcd.width(), lcd.height(), lcd.getColorDepth() );

  canvas->setColorDepth( lcd.getColorDepth() ); // hopefully color depth == 32

  fb = (uint32_t*)canvas->createSprite( canvasWidth, canvasHeight );

  plasma = (uint8_t *) malloc( canvasHeight * canvasWidth * sizeof ( uint8_t ) );

  if( fb == NULL || plasma == NULL ) {
    SDL_Log("Could not create plasma, halting");
    while(1) SDL_Delay(1000);
  }

  initPlasma();
}


void loop()
{
  for (int paletteShift = 0; paletteShift < 256; paletteShift+=2 ) {
    drawPlasma ( paletteShift );
    SDL_Delay(10);
  }
}

```

**Comment by Abbienew** [comment]
Hello 

I am wondering whether you develop ESP32 ScreenShot Receiver MacOs version ? thank you :)

**Comment by imliubo** [comment]
> Hello
> 
> I am wondering whether you develop ESP32 ScreenShot Receiver MacOs version ? thank you :)

Hi, this is not ESP32 ScreenShot Receiver or Sender, but maybe you can run LGFX on your MacBook directly with SDL.

**Comment by lovyan03** [comment]
@imliubo 
I haven't been able to try it yet because I don't have the environment to make this work, but I have merged it for the time being.
Thank you very much !

**Comment by imliubo** [comment]
Oh, sorry, I forget told you this pr still working in progress, recently I've been working on the CM4Stack project....
There are still some problems in the support of this PR that have not yet been fixed.

**Comment by tobozo** [comment]
@imliubo this is the `CMakeLists.txt` I came up with to have a github workflow compile the [example](https://github.com/lovyan03/LovyanGFX/tree/develop/examples_for_PC/CMake_SDL) on Windows, Linux and Mac: 


```cmake
cmake_minimum_required (VERSION 3.8)
project(LGFX_SDL)

set( LovyanGFX_DIR "../../../LovyanGFX/src" )
# set( SDL2_DIR  "C:/path/to/SDL2" )

add_definitions(-DLGFX_SDL)

file(GLOB Target_Files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS
    *.cpp
    ${LovyanGFX_DIR}/lgfx/Fonts/efont/*.c
    ${LovyanGFX_DIR}/lgfx/Fonts/IPA/*.c
    ${LovyanGFX_DIR}/lgfx/utility/*.c
    ${LovyanGFX_DIR}/lgfx/v1/*.cpp
    ${LovyanGFX_DIR}/lgfx/v1/misc/*.cpp
    ${LovyanGFX_DIR}/lgfx/v1/panel/Panel_Device.cpp
    ${LovyanGFX_DIR}/lgfx/v1/platforms/sdl/*.cpp
    )
add_executable (${PROJECT_NAME} ${Target_Files})

find_package(SDL2 REQUIRED)

message(STATUS "LGFX_SDL status:")
message(STATUS "    LovyanGFX dir       = ${LovyanGFX_DIR}")
message(STATUS "    SDL2 include path = ${SDL2_INCLUDE_DIRS}")
message(STATUS "    SDL2 libraries    = ${SDL2_LIBRARIES}")

target_include_directories(${PROJECT_NAME} PUBLIC ${LovyanGFX_DIR} ${SDL2_INCLUDE_DIRS})

if(UNIX)
  target_link_libraries(${PROJECT_NAME} -lpthread ${SDL2_LIBRARIES})
endif()

if(WIN32)
  set(CMAKE_CXX_COMPILER "clang++")
  target_link_libraries(${PROJECT_NAME} PUBLIC ${SDL2_LIBRARIES})
  # Copy the SDL .dll file into the application binary directory
  add_custom_command(
      TARGET ${PROJECT_NAME} POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy_if_different
      $<TARGET_FILE:SDL2::SDL2>
      $<TARGET_FILE_DIR:${PROJECT_NAME}>
      VERBATIM
  )
endif()


target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_17)

```

**Pull request merged**
