### PR TITLE
BallMaze: support M5Stack Core2

### PR DESCRIPTION
**Pull request by belm0**
(By the way, shouldn't the examples use LGFX_AUTODETECT to make it easy for most users?)

### CODE REVIEW

**Comment by lovyan03** [comment]
@belm0 
Thanks.
That example was made before AutoDetect was implemented and has not been fixed until now.
As you pointed out, it is easier to use AutoDetect and we will fix it soon.

**Comment by belm0** [comment]
Even if AutoDetect is added later, I think this PR is still useful now.  Please take a look.

**Comment by tobozo** [comment]
@belm0 thanks for your interest.

Only critital issues are patched directly on the master branch. 
Non critical patches should be submitted to the develop branch instead.

However as lovyan03 pointed out, adding an extra macro condition is the opposite of what is planned for this example.
Moreover, the macro you added enables pins 39/38 for M5Core2, but M5Core2 has no buttons.

If you want to patch this example, please submit changes using Autodetect as suggested, and do it on the develop branch.

The valid approach is to remove all '#if defined` statements and use a condition in the setup instead.

```C++
  switch( lcd.getBoard() ) {
    case lgfx::board_t::board_M5Stack:
      // this includes M5Fire
      BUTTON_A_PIN=39;
      BUTTON_B_PIN=38;
      draw_cycle = 3;
      zoom_min = 2;
      zoom_max = 32;
    break;
    case lgfx::board_t::board_M5StackCore2:
      // M5Core2 has not buttons, only touch!
      BUTTON_A_PIN=-1;
      BUTTON_B_PIN=-1;
      draw_cycle = 3;
      zoom_min = 2;
      zoom_max = 32;
    break;
    // (.. more configurations)
  }

  if( BUTTON_A_PIN != -1 ) {
    lgfx::lgfxPinMode(BUTTON_A_PIN, lgfx::pin_mode_t::input);
  }
  if( BUTTON_B_PIN != -1 ) {
    lgfx::lgfxPinMode(BUTTON_B_PIN, lgfx::pin_mode_t::input);
  }

```

**Comment by belm0** [comment]
Thank you.  First let's resolve this button mystery:

> Moreover, the macro you added enables pins 39/38 for M5Core2, but M5Core2 has no buttons.

This PR works fine on my Core2, and I'm able to control the game by the capacitance buttons.  Does that mean the Core2 firmware has some emulation of the Core Basic wired buttons?

So I think the Core Basic and Core2 can be treated identically as far as this demo.

**Comment by belm0** [comment]
> The valid approach is to remove all '#if defined` statements and use a condition in the setup instead.

If it's changed to runtime conditions, what about the case where autodetect doesn't work?

I thought autodetect can still be used with preprocessor conditions, by using `#define LGFX_AUTODETECT`.

**Comment by belm0** [comment]
I've corrected the PR to not set the button pins.  The existing code already handles the -1 sentinel.

**Comment by tobozo** [comment]
> what about the case where autodetect doesn't work?

Autodetect doesn't work when the device is not natively supported by LovyanGFX, or when the selected board in Arduino Boards Menu or platformio doesn't match reality.

In such situations the sketch should use a custom configuration, and obviously disable autodetect.

But this is out of scope for BallMaze.ino, detailed instructions about custom configuration is already explained in the [HowToUse/2_user_setting](https://github.com/lovyan03/LovyanGFX/blob/master/examples/HowToUse/2_user_setting/2_user_setting.ino) example sketch, and as said before the trend is to simplify the sketch, not to add more macros.

Maybe it's best to wait for lovyan03 to update the example.

**Pull request merged**
